on:
  push:
    branches:
      - main
  workflow_dispatch:
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - interface
          - core
          - authority
          - transport
          - validator
          - client
          - server
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release-please
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main
      # The logic below handles the npm publication:
      - name: Checkout
        uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
        if: ${{ steps.release.outputs.release_created }}
      - name: Install
        uses: bahmutov/npm-install@v1
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: |
          cd packages/${{ matrix.package }}
          npm publish --access=public
