name: transport

on:
  push:
    branches:
      - main
    paths:
      - "packages/core/**"
      - "packages/interface/**"
      - "packages/transport/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/core/**"
      - "packages/interface/**"
      - "packages/transport/**"
      - ".github/workflows/transport.yml"
jobs:
  check:
    name: Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
        project:
          - transport
    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.2

      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: packages/${{matrix.project}}/tsconfig.json
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 14
          - 16
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        project:
          - transport

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.2

      - name: Test (Node)
        run: nnpm run --if-present --dir packages/${{matrix.project}} test:node

      - name: Test (Web)
        run: nnpm run --if-present --dir packages/${{matrix.project}} test:web
